# version: 2.1
# executors:
#   node:
#     docker:
#       - image: circleci/node:10
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test
# jobs:
#   build:
#     executor: node
#     steps:
#       - checkout
#       - run: npm install
#       - run: npm run build
#   test:
#     executor: node
#     steps:
#       - checkout
#       - run: npm install
#       - run: npm run test


version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:4.8.2 # ...with this image as the primary container; this is where all `steps` will run
      - image: mongo:3.4.4 # and this image as the secondary service container
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: "sudo npm install -g n"
      - run:
          name: update-npm
          command: "sudo n stable"
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "server/package.json" }}
      - run:
          name: install-npm-wee
          command: cd server && npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "server/package.json" }}
          paths:
            - server/node_modules
      - run: # run tests
          name: test
          command: npm test